# Generated by Django 2.2.6 on 2019-12-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpage',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
