# Generated by Django 2.2.6 on 2019-12-11 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0003_remove_artpage_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpage',
            name='artist',
            field=models.ForeignKey(default=None, help_text='The Artist who posted this', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
