# Generated by Django 2.2.6 on 2019-12-28 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20191211_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpage',
            name='short_desc',
            field=models.CharField(default=django.utils.timezone.now, help_text='A short description to display on the main page.', max_length=1000),
            preserve_default=False,
        ),
    ]
